### ISSUE TITLE
我每10s添加4个弹幕到屏幕，为什么第一次添加的的时候数量都有问题？？都是少于4个？？谢谢，帮忙卡看下

### ISSUE THREAD

**Issue by zhongmichael** [xujiaji/DMView2#12]

**Comment by xujiaji** [comment]
你好请问你是怎么添加的呢？方便看一下添加部分的逻辑么，方便模拟一下你所在的问题

**Comment by zhongmichael** [comment]
你好！就是一个简单的定时器  没隔 10s添加五个弹幕，但是第一次安装的时候经常显示到屏幕的就不是5个 有时5个 有时4个  有时3个？？？这是为什么？
mCustomTimer = new CustomTimer(10000) {
            @Override
            public void onTick() {
                addDM("小明11", "1111111111111111111111111111111111 11111111111 ", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=3512331237,2033775251&fm=27&gp=0.jpg");
                addDM("小明21", "21212121212121212121212121212121212121消息2 sdaf", "https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1881776517,987084327&fm=27&gp=0.jpg");
                addDM("小明31", "31313131313131313131313131313131313131313消息3dsfabcdefghi", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=16550438,2220103346&fm=27&gp=0.jpg");
                addDM("小明41", "4141414141414141414141414141414141414141414141414141414141414消息4ds", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2237097328,2363045038&fm=27&gp=0.jpg");
                addDM("小明51", "51515151515151515151515151515151515151515151515151消息5", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=586574978,3261086036&fm=27&gp=0.jpg");
            }
        };
        mCustomTimer.start();

**Comment by zhongmichael** [comment]
后面的显示数量是正确的  每次五个都添加上去了  ,只有第一次添加的时候 经常会出现少弹幕的情况

**Comment by xujiaji** [comment]
这是我刚刚打包的apk文件，你下载安装试试呢？点击首页的轮询添加5个弹幕，好像没有遇到你的问题
[sample-debug.zip](https://github.com/xujiaji/DMView2/files/3032933/sample-debug.zip)

> 下面是首页java代码：
 
``` java
public class MainActivity extends AppCompatActivity {

    private DMSurfaceView dmSurfaceView;
    private DMSurfaceView dmAnnouncement;
    private DMSurfaceView dmAnnouncement2;
    private DMSurfaceView dmAnnouncement3;
    private DMSurfaceView dmAnnouncement4;
    private CheckBox checkBox;
    private final Handler handler = new Handler();

    private Runnable runnable;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        dmSurfaceView = findViewById(R.id.dmView);
        dmAnnouncement = findViewById(R.id.dmAnnouncement);
        dmAnnouncement2 = findViewById(R.id.dmAnnouncement2);
        dmAnnouncement3 = findViewById(R.id.dmAnnouncement3);
        dmAnnouncement4 = findViewById(R.id.dmAnnouncement4);

        checkBox = findViewById(R.id.checkbox);

        dmSurfaceView.getController().setOnDMAddListener(new OnDMAddListener() {
            @Override
            public void added(BaseDmEntity dmEntity) {

            }

            @Override
            public void addedAll() {
                Log.e("MainActivity", "thread: " + Thread.currentThread().getName());
                Toast.makeText(MainActivity.this, "弹幕该轮显示完毕", Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    protected void onPause() {
        super.onPause();
        LogUtil.e("MainActivity onPause()");
        dmSurfaceView.getController().pause();
        dmAnnouncement.getController().pause();
        dmAnnouncement2.getController().pause();
        dmAnnouncement3.getController().pause();
        dmAnnouncement4.getController().pause();
        if (runnable != null) {
            handler.removeCallbacks(runnable);
            runnable = null;
        }
    }

    public void onClickAddDM(View view) {
        dmAnnouncement.getController().add(LayoutInflater.from(this).inflate(R.layout.announcement_text, null));

        dmAnnouncement.getController().setOnDMAddListener(new OnDMAddListener() {
            @Override
            public void added(BaseDmEntity dmEntity) {
                dmAnnouncement.getController().add(LayoutInflater.from(MainActivity.this).inflate(R.layout.announcement_text, null));
            }

            @Override
            public void addedAll() {

            }
        });


        dmAnnouncement2.getController().add(LayoutInflater.from(this).inflate(R.layout.announcement_text, null));

        dmAnnouncement3.getController().add(LayoutInflater.from(this).inflate(R.layout.announcement_image_text, null));

        dmAnnouncement4.getController().add(LayoutInflater.from(this).inflate(R.layout.announcement_image_text, null));

        addDM("小明1", "一条消息abcdefghijklmnopqrstuvwxyz123456789 一条消息abcdefghijklmnopqrstuvwxyz123456789 ", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=3512331237,2033775251&fm=27&gp=0.jpg");
        addDM("小明2", "消息2 sdaf", "https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1881776517,987084327&fm=27&gp=0.jpg");
        addDM("小明3", "消息3dsfabcdefghijklmnopqrstuvwxyz123456789", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=16550438,2220103346&fm=27&gp=0.jpg");
        addDM("小明4", "消息4ds", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2237097328,2363045038&fm=27&gp=0.jpg");
        addDM("小明5", "消息5", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=586574978,3261086036&fm=27&gp=0.jpg");

        addDM("小明6", "消息  6", "https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=3185942390,3143936596&fm=27&gp=0.jpg");
        addDM("小明7", "消  息7abcdefghijklmnopqrstuvwxyz123456789", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1137298932,366992998&fm=27&gp=0.jpg");
        addDM("小明8", "消息8", "https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=1727532235,3210820490&fm=27&gp=0.jpg");
        addDM("小明9", "消 息9", "https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=782046930,1105099424&fm=27&gp=0.jpg");
        addDM("小明10", "这是最后到消息 10", "https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=73760354,2094376027&fm=27&gp=0.jpg");
    }


    public void onClickAdd5NoOver(View view) {
        if (runnable == null) {
            runnable = new Runnable() {
                @Override
                public void run() {
                    addDM("小明11", "1111111111111111111111111111111111 11111111111 ", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=3512331237,2033775251&fm=27&gp=0.jpg");
                    addDM("小明21", "21212121212121212121212121212121212121消息2 sdaf", "https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1881776517,987084327&fm=27&gp=0.jpg");
                    addDM("小明31", "31313131313131313131313131313131313131313消息3dsfabcdefghi", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=16550438,2220103346&fm=27&gp=0.jpg");
                    addDM("小明41", "4141414141414141414141414141414141414141414141414141414141414消息4ds", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2237097328,2363045038&fm=27&gp=0.jpg");
                    addDM("小明51", "51515151515151515151515151515151515151515151515151消息5", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=586574978,3261086036&fm=27&gp=0.jpg");

                    if (runnable != null) {
                        handler.postDelayed(runnable, 10000);
                    }
                }
            };
            handler.post(runnable);
        }
    }

    private void addDM(String name, String msg, String imgUrl) {
        final View templateView = LayoutInflater.from(this).inflate(R.layout.barrage, null);
        final ViewHolder mViewHolder = new ViewHolder(templateView);
        mViewHolder.tvBarrageName.setText(name);
        mViewHolder.tvBarrageMsg.setText(msg);
//        mViewHolder.imgBarrageHead.setImageBitmap(bitmap);
        final AtomicInteger atomicInteger = new AtomicInteger();
        final Random random = new Random();
        Glide.with(this)
                .load(imgUrl)
                .into(new SimpleTarget<Drawable>() {
                    @Override
                    public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                        mViewHolder.imgBarrageHead.setImageDrawable(resource);
                        dmSurfaceView.getController().add(templateView);

                        if (!checkBox.isChecked()) {
                            return;
                        }
                        int num = atomicInteger.get() + 1;
                        if (num < random.nextInt(10)) {
                            dmSurfaceView.getController().add(new ViewCreator() {
                                @Override
                                public View build() {
                                    return LayoutInflater.from(MainActivity.this).inflate(R.layout.barrage_other, null);
                                }
                            });
                        }
                        atomicInteger.set(num);
                    }
                });
    }

    public void onClickGoTestDMTextureView(View view) {
        startActivity(new Intent(this, TestTextureActivity.class));
    }

    public void onClickClearScreen(View view) {
        dmSurfaceView.getController().destroy();
    }

    private static class ViewHolder {
        TextView tvBarrageName;
        TextView tvBarrageMsg;
        ImageView imgBarrageHead;

        ViewHolder(View view) {
            tvBarrageName = view.findViewById(R.id.tvBarrageName);
            tvBarrageMsg = view.findViewById(R.id.tvBarrageMsg);
            imgBarrageHead = view.findViewById(R.id.imgBarrageHead);
        }
    }
}

```

**Comment by zhongmichael** [comment]
public abstract class CustomTimer {
    private static final int MSG = 1;
    private final long mCountdownInterval;
    private boolean isStop = false;
    private boolean isPause = false;
    private Handler mHandler = new Handler() {
        public void handleMessage(Message msg) {
            if (msg.what == MSG) {
                synchronized (CustomTimer.this) {
                    if (!CustomTimer.this.isStop && !CustomTimer.this.isPause) {
                        CustomTimer.this.onTick();
                        this.sendMessageDelayed(this.obtainMessage(1), mCountdownInterval);
                    }
                }
            }
        }
    };

    public CustomTimer(long countDownInterval) {
        this.mCountdownInterval = countDownInterval;
    }

    private synchronized CustomTimer startTimer() {
        this.isStop = false;
        this.mHandler.sendMessage(this.mHandler.obtainMessage(MSG));
        return this;
    }

    public final synchronized void start() {
        this.startTimer();
    }

    public final synchronized void stop() {
        this.isStop = true;
        this.mHandler.removeMessages(MSG);
    }

    public final synchronized void pause() {
        if (!this.isStop) {
            this.isPause = true;
            this.mHandler.removeMessages(MSG);
        }
    }

    public final synchronized void restart() {
        if (!this.isStop && this.isPause) {
            this.isPause = false;
            this.startTimer();
        }
    }

    public abstract void onTick();

}


public class MainActivity extends AppCompatActivity {

    private DMSurfaceView dmSurfaceView,dmSurfaceView2;
    private Context mContext;
    CustomTimer mCustomTimer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mContext = this;
        setContentView(R.layout.activity_main);
        dmSurfaceView = findViewById(R.id.dmView);
        dmSurfaceView2 = findViewById(R.id.dmView2);


        dmSurfaceView.getController().setOnDMAddListener(new OnDMAddListener() {
            @Override
            public void added(BaseDmEntity dmEntity) {

            }

            @Override
            public void addedAll() {
                Log.e("MainActivity", "thread: " + Thread.currentThread().getName());
            }
        });

        mCustomTimer = new CustomTimer(20000) {
            @Override
            public void onTick() {
                addDM("小明11", "1111111111111111111111111111111111 11111111111 ", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=3512331237,2033775251&fm=27&gp=0.jpg");
                addDM("小明21", "21212121212121212121212121212121212121消息2 sdaf", "https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1881776517,987084327&fm=27&gp=0.jpg");
                addDM("小明31", "31313131313131313131313131313131313131313消息3dsfabcdefghi", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=16550438,2220103346&fm=27&gp=0.jpg");
                addDM("小明41", "4141414141414141414141414141414141414141414141414141414141414消息4ds", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2237097328,2363045038&fm=27&gp=0.jpg");
                addDM("小明51", "51515151515151515151515151515151515151515151515151消息5", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=586574978,3261086036&fm=27&gp=0.jpg");
            }
        };
        mCustomTimer.start();
    }

    private void addDM(String name, String msg, String imgUrl) {
        final View templateView = LayoutInflater.from(this).inflate(R.layout.barrage, null);
        final ViewHolder mViewHolder = new ViewHolder(templateView);
        mViewHolder.tvBarrageName.setText(name);
        mViewHolder.tvBarrageMsg.setText(msg);
//        mViewHolder.imgBarrageHead.setImageBitmap(bitmap);
        if (((MainActivity) mContext).isDestroyed() || ((MainActivity) mContext).isFinishing())
            return;
        Glide.with(mContext)
                .load(imgUrl)
                .into(new SimpleTarget<Drawable>() {
                    @Override
                    public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                        mViewHolder.imgBarrageHead.setImageDrawable(resource);
                        dmSurfaceView.getController().add(templateView);
                    }
                });
    }


    @Override
    protected void onPause() {
        super.onPause();
        LogUtil.e("MainActivity onPause()");
        dmSurfaceView.getController().pause();
        dmSurfaceView.getController().destroy();
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (null != mCustomTimer) {
            mCustomTimer.pause();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (null != mCustomTimer) {
            mCustomTimer.restart();
        }
    }

    public void onClickAddDM(View view) {
        addDM("小明1", "一条消息abcdefghijklmnopqrstuvwxyz123456789 一条消息abcdefghijklmnopqrstuvwxyz123456789 ", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=3512331237,2033775251&fm=27&gp=0.jpg");
        addDM("小明2", "消息2 sdaf", "https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1881776517,987084327&fm=27&gp=0.jpg");
        addDM("小明3", "消息3dsfabcdefghijklmnopqrstuvwxyz123456789", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=16550438,2220103346&fm=27&gp=0.jpg");
        addDM("小明4", "消息4ds", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2237097328,2363045038&fm=27&gp=0.jpg");
        addDM("小明5", "消息5", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=586574978,3261086036&fm=27&gp=0.jpg");

        addDM("小明6", "消息  6", "https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=3185942390,3143936596&fm=27&gp=0.jpg");
        addDM("小明7", "消  息7abcdefghijklmnopqrstuvwxyz123456789", "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1137298932,366992998&fm=27&gp=0.jpg");
        addDM("小明8", "消息8", "https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=1727532235,3210820490&fm=27&gp=0.jpg");
        addDM("小明9", "消 息9", "https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=782046930,1105099424&fm=27&gp=0.jpg");
        addDM("小明10", "这是最后到消息 10", "https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=73760354,2094376027&fm=27&gp=0.jpg");
    }


    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (null != mCustomTimer) {
            mCustomTimer.stop();
        }
    }
    public void onClickGoTestDMTextureView(View view) {
        startActivity(new Intent(this, TestTextureActivity.class));
    }

    public void onClickClearScreen(View view) {
        dmSurfaceView.getController().destroy();
    }

    public void onPauseClearScreen(View view) {
        dmSurfaceView.getController().pause();
    }

    private static class ViewHolder {
        TextView tvBarrageName;
        TextView tvBarrageMsg;
        ImageView imgBarrageHead;

        ViewHolder(View view) {
            tvBarrageName = view.findViewById(R.id.tvBarrageName);
            tvBarrageMsg = view.findViewById(R.id.tvBarrageMsg);
            imgBarrageHead = view.findViewById(R.id.imgBarrageHead);
        }
    }

}


你好  你可以用我的这个代码跑一下 ~~~一下就能复现  第一次少弹幕的情况

**Comment by zhongmichael** [comment]
你这个弹幕我是了一下  没问题    你可以把弹幕内容搞长一点  看下会不会出现这个问题  我这边弹幕长了感觉很容易复现

**Comment by zhongmichael** [comment]
你发过来的也出现了，，第一次出来只有四个？？经常出现  杀应用重启  很大的概率出现

**Comment by zhongmichael** [comment]
我截图了  你看下  第一次只出现三行的时候就出现这个问题了

**Comment by zhongmichael** [comment]
你好 ！你的包你复现了吗？是会有出现吧  多点几次就出现了，

**Comment by xujiaji** [comment]
刚刚修复了一下，线程没有同步的问题。下载主分支试试，我这块比较薄弱😂

**Comment by zhongmichael** [comment]
enen   是的  就是线程同步问题  我昨天也加了后面没发现问题了
还有一个问题  你这个弹幕不能设置弹幕的轨道数量 有时显示不全

**Comment by xujiaji** [comment]
什么弹幕轨道数量？

**Comment by zhongmichael** [comment]
就是固定 弹幕的行数

**Comment by xujiaji** [comment]
哦哦，因该是高度没有算好。可以截图一下你显示不全的情况吗
