### ISSUE TITLE
比较的时候  空了  #24908 java.lang.NullPointerException 

### ISSUE THREAD

**Issue by Leavds** [xujiaji/DMView2#13]
#24908 java.lang.NullPointerException
Attempt to read from field 'int com.xujiaji.dmlib2.entity.BaseDmEntity.priority' on a null object reference
com.xujiaji.dmlib2.entity.BaseDmEntity.compareTo(BaseDmEntity.java:65)

1 com.xujiaji.dmlib2.entity.BaseDmEntity.compareTo(BaseDmEntity.java:65)
--
2 com.xujiaji.dmlib2.entity.BaseDmEntity.compareTo(BaseDmEntity.java:30)
3 java.util.PriorityQueue.siftUpComparable(PriorityQueue.java:656)
4 java.util.PriorityQueue.siftUp(PriorityQueue.java:647)
5 java.util.PriorityQueue.offer(PriorityQueue.java:344)
6 java.util.PriorityQueue.add(PriorityQueue.java:321)
7 com.xujiaji.dmlib2.widget.Controller.addToQueue(Controller.java:222)
8 com.xujiaji.dmlib2.widget.Controller$2.run(Controller.java:215)
9 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11 java.lang.Thread.run(Thread.java:764)

**Comment by xujiaji** [comment]
下载主分支，导入项目试试呢？这个之前修复过

**Comment by Leavds** [comment]
ok
