### ISSUE TITLE
锁屏打开App弹幕卡死又重新创建了

### ISSUE THREAD

**Issue by Chen-Xi-g** [xujiaji/DMView2#3]

**Comment by xujiaji** [comment]
可以试试用DMTextureView

**Comment by Chen-Xi-g** [comment]
> 可以试试用DMTextureView
使用DMTextureView有一种卡顿的感觉

**Comment by xujiaji** [comment]
晚上我检查一下怎么回事，你这边有什么建议吗？

**Comment by Chen-Xi-g** [comment]
非常感谢，希望可以设置每一行弹幕与上一行弹幕出现的时间间隔

**Comment by Chen-Xi-g** [comment]
感觉有些耗内存，期待优化

**Comment by xujiaji** [comment]
好的，因为一直没有项目能用到自己这个东西。很多方面可能都有考虑不周的地方

**Comment by xujiaji** [comment]
你直接在这里下载[dmlib2](https://github.com/xujiaji/DMView2/blob/master/dmlib2)导入项目看一下，重新创建的问题可以了

**Comment by Chen-Xi-g** [comment]
非常感谢。

**Comment by xujiaji** [comment]
性能和你说的间隔问题周末再看看！
现在的实现方式是用的三张SurfaceView那么大的画布用来交替展示，确实很占用内存。
我暂时还莫得好的想法，你呢？

**Comment by Chen-Xi-g** [comment]
我在Email给您发送了一段视频，使用dmlib2还是会发生卡屏情况。

**Comment by xujiaji** [comment]
看到了，闪了一下

**Comment by xujiaji** [comment]
试试看把cancel改成end，重新解锁后会不会闪一下
![image](https://user-images.githubusercontent.com/16447251/50415281-248d6780-0855-11e9-92eb-b2c7834a393a.png)

**Comment by Chen-Xi-g** [comment]
哦，天哪，
![image](https://user-images.githubusercontent.com/37918545/50419666-e9972e00-086c-11e9-8354-5ee4f99d5707.png)   发生了OOM

**Comment by xujiaji** [comment]
抱歉抱歉:sweat_smile:
我写的方式太耗内存了，周末重写一下

**Comment by Chen-Xi-g** [comment]
非常感谢，我如今正在查找OOM的原因

**Comment by xujiaji** [comment]
我创建了三个surfaceview那么大的bitmap就已经很耗内存了

**Comment by Chen-Xi-g** [comment]
请问有好的解决方案了吗? 现在太耗内存了，长时间不操作OOM

**Comment by xujiaji** [comment]
方案有啦！还在写

**Comment by xujiaji** [comment]
今或明天因该可以完成从右到左，你可以先用着:smile:

**Comment by Chen-Xi-g** [comment]
非常感谢

**Comment by Chen-Xi-g** [comment]
请问现在的弹幕如何手动取消所有弹幕

**Comment by xujiaji** [comment]
没考虑这个功能，你可以销毁SurfaceView

**Comment by xujiaji** [comment]
https://github.com/xujiaji/DMView2/tree/dev/dmlib2

下载上面这个替换你项目中的本框架，试试看。现在已经非常流畅了，内存消耗大幅度降低。
目前只测试了SurfaceView从右到左的功能。
如果你要清楚弹幕，现在直接调用Controller中的`destory()`方法就行了

**Comment by Chen-Xi-g** [comment]
好的，谢谢，我现在正在对项目进行更改

**Comment by Chen-Xi-g** [comment]
太棒了！完美，膜拜大神

**Comment by xujiaji** [comment]
好的，那你先将就一下哈！如果有什么需要可以提，如果适合话我会加进去

**Comment by Chen-Xi-g** [comment]
SurfaceView锁屏后弹幕还是会卡在屏幕上，如果调用了destory()再次开启弹幕会发生抽搐行为。。。再次destory()弹幕正常

**Comment by xujiaji** [comment]
是一直卡在屏幕上吗？我这边测试的时候是继续运行的，怎么个卡法

**Comment by Chen-Xi-g** [comment]
或者弹幕卡屏后切换到home也会恢复正常

**Comment by Chen-Xi-g** [comment]
稍等我给你邮箱发送视频

**Comment by xujiaji** [comment]
[sample-debug.zip](https://github.com/xujiaji/DMView2/files/2725985/sample-debug.zip)

**Comment by xujiaji** [comment]
你试试这个

**Comment by Chen-Xi-g** [comment]
安装你发送的apk还是会发生同样的情况

**Comment by xujiaji** [comment]
你用的什么型号的手机

**Comment by Chen-Xi-g** [comment]
红米6 pro

**Comment by xujiaji** [comment]
![image](https://user-images.githubusercontent.com/16447251/50676038-07168580-102d-11e9-8918-9668811ee8ad.png)

**Comment by Chen-Xi-g** [comment]
已重新发送到你的QQ Email

**Comment by xujiaji** [comment]
怎么之前的就贴在上面了:sweat_smile:

**Comment by Chen-Xi-g** [comment]
这个我也不是很清楚，只要锁屏之后就会变成这样

**Comment by xujiaji** [comment]
[sample-debug.zip](https://github.com/xujiaji/DMView2/files/2726412/sample-debug.zip)

**Comment by xujiaji** [comment]
你安装其他手机试试看呢？我试了几个手机好像没有问题。回去我再查查

**Comment by Chen-Xi-g** [comment]
好的 我现在试一下

**Comment by Chen-Xi-g** [comment]
SurfaceView还是这样。锁屏就会卡在屏幕上。但是TextureView没有问题，可是TextureView的弹幕速度非常快设置多少的值都没有变化

**Comment by Chen-Xi-g** [comment]
我安装你发的安装包了  SurfaceView锁屏就会卡在屏幕  也许是手机的问题吧，。

**Comment by xujiaji** [comment]
那你先用TextureView，这个速度可以调。我更新一下代码

**Comment by xujiaji** [comment]
https://github.com/xujiaji/DMView2/tree/dev/dmlib2
通过下面两个值的改变可以调节速度，占时你就直接改这两值吧

![image](https://user-images.githubusercontent.com/16447251/50683401-e827eb80-104c-11e9-872d-7b4620e6009d.png)

**Comment by Chen-Xi-g** [comment]
好的 谢谢

**Comment by xujiaji** [comment]
试试看这个Demo有没有之前的问题呢
[sample-debug.zip](https://github.com/xujiaji/DMView2/files/2735168/sample-debug.zip)

**Comment by Chen-Xi-g** [comment]
这个Demo没有问题

**Comment by xujiaji** [comment]
已更新，直接依赖使用就可以了。改了一些xml属性名，你可能需要注意一下，可以看一下文档或案例。
```
implementation 'com.github.xujiaji:dmlib2:0.0.5'
```
