### ISSUE TITLE
如果需要内容循环滚屏应该一直定时addDM吗？

### ISSUE THREAD

**Issue by lofty14** [xujiaji/DMView2#4]
有没有方式能获取到弹幕即将播放完的回调之类的呢

**Comment by lofty14** [comment]
还有一个问题，滚屏速度调慢之后，滚动的时候会感觉特别闪，可以通过调帧率的方式优化吗

**Comment by xujiaji** [comment]
有一个监听`setOnDMAddListener`每添加一个弹幕在屏幕上就会回调`void added(BaseDmEntity dmEntity)`；如果是你这需求可以这么操作：每次回调这个方法的时候，你就添加一个进去

**Comment by xujiaji** [comment]
关于第二个问题，您当前设置的`dm_span`和`dm_sleep`是多少呢？我也试试，微调一下是否能到到效果？

**Comment by lofty14** [comment]
希望是app:dm_sleep="50"
app:dm_span="2dp"
除非sleep到10，就不会有明显的闪烁了

**Comment by xujiaji** [comment]
用的是DMTextureView还是DMSurfaceView，父布局是什么呢？

**Comment by lofty14** [comment]
父布局是RelativeLayout，用的DMSurfaceView，还有那个setOnDMAddListener，DM还没开始显示，就执行回调了，不介意的话可否加qq更方便，我的是289637104，谢啦

**Comment by xujiaji** [comment]
好的
