### ISSUE TITLE
大神，我这边需要在弹幕框头像周围添加星星闪烁动画

### ISSUE THREAD

**Issue by Leavds** [xujiaji/DMView2#5]
第一种直接glide  加载 gif   第二种  写个anim动画  这个  动画的 加入 移除  该往哪写

**Comment by Leavds** [comment]
我试了下添加缩放anim和 gif动画图 都不行，大神 有什么好的解决方案吗

**Comment by xujiaji** [comment]
这个恐怕得考虑自定义一个viewgroup来的方便点

**Comment by Leavds** [comment]
大神，我们这边之前的处理方式是 自定义viewgroup  做了一个平移动画处理，平移的时候略有卡顿

**Comment by xujiaji** [comment]
如果要在这里面用，恐怕我得好好想想了。你有什么思路吗

**Comment by Leavds** [comment]
canvas循环绘制动画，我这边是画的有点懵

**Comment by xujiaji** [comment]
gif多张图片切换来实现？

**Comment by Leavds** [comment]
canvas  画的话，写个循环不停的加减高度绘制，gif应该只能在自定义layout里了，这是一个画线的

for (int i = 0; i < barNum - 1; i++) {
            float height = (Float) (animList.get(i).getAnimatedValue());
            canvas.drawRect(
                    (float) (i * sumWidth), // left
                    canvas.getHeight() - height,//height, // top
                    (float) (i * sumWidth + barWidth), // right
                    canvas.getHeight(), // bottom
                    paint // Paint
            );
        }

**Comment by xujiaji** [comment]
没明白你的意思，不停加减高度干嘛

**Comment by Leavds** [comment]
这样用不停的绘制，用canvas做动画啊，或者 还有其他方案 ？

**Comment by xujiaji** [comment]
我想想，之前没考虑动画，因为本没打算做的太复杂。复杂的你用bilibili的烈焰弹幕使试试？

**Comment by Leavds** [comment]
这个 后面再看看
