### ISSUE TITLE
大神 再问个就是  你这边在 onWindowFocusChanged做的 prepare()和pause（）

### ISSUE THREAD

**Issue by Leavds** [xujiaji/DMView2#7]
界面弹出dialog失去焦点弹幕view  直接就隐藏了，我们这收发礼物或者发送弹幕就看不到弹幕动画了，我这边现在处理是把这个 prepare()放到fragemnt的onrestat，pause（）放在onstop  或者onpause里，这样可以么

**Comment by xujiaji** [comment]
可以的，下载源码注释掉，在fragment或对应周期调用就可以

**Comment by Leavds** [comment]
好的

**Comment by Leavds** [comment]
这样
