### ISSUE TITLE
大神   你这个弹幕view 是飘在当前界面的最顶层，把其他的都覆盖了

### ISSUE THREAD

**Issue by Leavds** [xujiaji/DMView2#8]
怎么处理，让弹幕view 显示在当前layout所设置的层级处，我们这有个问题 ，就是弹幕把最牛逼的大礼物挡住了

**Comment by xujiaji** [comment]
用dmtextureview试试？

**Comment by Leavds** [comment]
666  解决了

**Comment by Leavds** [comment]
这样是可以解决层级问题，又引出个问题就是上下滑动切换直播间的时候，之前房间发过弹幕到下个房间弹幕ui是个大黑框，有了新的弹幕黑框才隐藏

**Comment by xujiaji** [comment]
如果方便截个图吧！想象力不大好 - -

**Comment by Leavds** [comment]
![image](https://user-images.githubusercontent.com/26810069/54405125-89e44c80-4710-11e9-8281-694100dd2275.png)

**Comment by xujiaji** [comment]
在`DMTextureView`的`onSurfaceTextureAvailable()`方法最后加一句这个试试：`mController.draw(0, true);`

**Comment by Leavds** [comment]
哦了，专业啊
